#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

pkill apache2

chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Start Nginx as nginx user
sudo -u nginx service nginx start
