#!/usr/bin/env bash
#Installing Nginx and configuring it

sudo apt update -y
sudo apt install nginx -y

sudo systemctl enable nginx
sudo systemctl start nginx

sudo sed -i "/server_name _;/a \    add_header X-Served-By '"$(hostname)"';" /etc/nginx/sites-available/default

sudo systemctl restart nginx

