#!/usr/bin/env bash
# Installing Nginx on a server

sudo apt-get update
sudo apt-get install -y nginx

sudo apt-get install ufw
sudo ufw allow 'Nginx HTTP'

echo 'Holberton School' | sudo tee /var/www/html/index.html

sudo service restart nginx
