#!/usr/bin/env bash
# Commands to automatically configure a Ubuntu machine to handle redirection

sudo apt-get update -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
